### ISSUE TITLE
[Suggestion] More GUIs

### ISSUE THREAD

**Issue by BroCrows** [Skintrphoenix/CustomGUI#1]
Is it possible to add more GUIs(example 2 hopper GUIs) if not could you make it possible. Maybe like a config where you can say like
```
Double_Chest:
  - doublechest.yml
  - customnamedoublechest.yml
Chest:
  - chest.yml
  - customnamechest.yml
Hopper:
  - hopper.yml
  - customnamehopper.yml
```
Also putting it in folders(like a hopper folder with hopper GUIs) would be nice!

**Comment by Skintrphoenix** [comment]
Okay, i can make it

**Comment by Skintrphoenix** [comment]
I have 1 question, what do you mean hopper.yml and customnamehopper.yml? I don't understand

**Comment by BroCrows** [comment]
A custom name for the .yml so you can organize it better(eg warps.yml)

**Comment by ZZWILLIAMXXTrue** [comment]
> I have 1 question, what do you mean hopper.yml and customnamehopper.yml? I don't understand

Ohhhh I see what you mean now, I meant to put hopper...

**Comment by Skintrphoenix** [comment]
the contents of the config are the same, but the name of the config is different?

**Comment by BroCrows** [comment]
yes, would that be possible, if its not you could just put it all into one config. Though im pretty sure its possible.

**Comment by Skintrphoenix** [comment]
I can make it, i create a new php file, because, the file main it's so lag

**Comment by Skintrphoenix** [comment]
how many gui would i want to make?

**Comment by Skintrphoenix** [comment]
like 2 gui type hopper or 3 gui type chest
